### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by noxtalk** [JunoLab/atom-bombe#1]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.3
**System**: Debian GNU/Linux
**Thrown From**: [bombe](https://github.com/JunoLab/atom-bombe) package, v0.1.0
### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:993

Error: Can't save buffer with no file path
    at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:993:15)
    at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:988:19)
    at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:579:26)
    at /home/xango/.atom/packages/bombe/lib/bombe.coffee:78:14
    at Dialog.d.onConfirm (/home/xango/.atom/packages/bombe/lib/bombe.coffee:50:20)
    at space-pen-div.atom.commands.add.core:confirm (/home/xango/.atom/packages/bombe/lib/dialog.coffee:48:26)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:241:29)
    at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
```
### Commands

```
     -0:08.5.0 command-palette:toggle (atom-text-editor.editor.is-focused)
     -0:03.9.0 bombe:encrypt-this-file (atom-text-editor.editor)
     -0:00.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
bombe, v0.1.0

# Dev
No dev packages
```

**Comment by noxtalk** [comment]
DOnt work.
I need help with this error.
Thanks

**Comment by MikeInnes** [comment]
Thanks for reporting – you should find that this is fixed if you update the package.
